excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://maniesco.github.io
title: Chris Paul Hlad
email: maniesco@gmail.com
author: maniesco
description: My awesome new site
paginate: 3
google_analytics: 